const SUBJECTS = [
  {
    id: 'english',
    name: 'Use of English',
    emoji: '📖',
    color: '#1b2a4a',
    topics: [
      'Comprehension Passages',
      'Summary Writing',
      'Lexis and Structure',
      'Oral English & Phonology',
      'Essay Writing',
      'Concord (Agreement)',
      'Idioms and Phrasal Verbs',
      'Register and Diction',
      'Sentence Interpretation',
      'Antonyms and Synonyms',
    ],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    emoji: '📐',
    color: '#2e4a7a',
    topics: [
      'Number Bases',
      'Indices and Logarithms',
      'Surds',
      'Fractions and Decimals',
      'Algebra — Expressions',
      'Quadratic Equations',
      'Linear and Simultaneous Equations',
      'Polynomials',
      'Inequalities',
      'Progression (AP & GP)',
      'Trigonometry',
      'Coordinate Geometry',
      'Differentiation and Integration',
      'Permutation and Combination',
      'Probability',
      'Statistics — Mean, Median, Mode',
      'Set Theory',
      'Matrices and Determinants',
      'Mensuration — Area and Volume',
      'Geometry — Circles and Triangles',
    ],
  },
  {
    id: 'physics',
    name: 'Physics',
    emoji: '⚡',
    color: '#1b2a4a',
    topics: [
      'Measurement and Units',
      'Scalars and Vectors',
      'Linear Motion and Kinematics',
      'Projectile Motion',
      'Newton\'s Laws of Motion',
      'Work, Energy and Power',
      'Friction',
      'Simple Machines',
      'Elasticity',
      'Pressure in Fluids',
      'Waves — Types and Properties',
      'Sound Waves',
      'Light — Reflection and Refraction',
      'Lenses and Mirrors',
      'Heat and Temperature',
      'Gas Laws',
      'Electricity — Current and Voltage',
      'Ohm\'s Law and Resistance',
      'Capacitors',
      'Magnetic Fields',
      'Electromagnetic Induction',
      'Radioactivity and Nuclear Physics',
      'Modern Physics',
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    emoji: '⚗️',
    color: '#2e4a7a',
    topics: [
      'Atomic Structure',
      'Periodic Table and Periodicity',
      'Chemical Bonding',
      'Stoichiometry and Mole Concept',
      'Acids, Bases and Salts',
      'Oxidation and Reduction (Redox)',
      'Electrochemistry',
      'Kinetics — Rate of Reaction',
      'Chemical Equilibrium',
      'States of Matter',
      'Gas Laws',
      'Solutions and Solubility',
      'Organic Chemistry — Hydrocarbons',
      'Alkanols and Alkanoic Acids',
      'Esters and Fats',
      'Carbohydrates',
      'Polymers',
      'Environmental Chemistry',
      'Metals and Their Compounds',
      'Non-metals — Nitrogen, Oxygen, Chlorine',
    ],
  },
  {
    id: 'biology',
    name: 'Biology',
    emoji: '🧬',
    color: '#1b2a4a',
    topics: [
      'Cell Structure and Organisation',
      'Cell Division — Mitosis and Meiosis',
      'Diffusion, Osmosis and Active Transport',
      'Nutrition in Plants',
      'Nutrition in Animals',
      'Digestive System',
      'Circulatory System',
      'Respiratory System',
      'Excretory System',
      'Nervous System',
      'Hormonal System',
      'Reproductive System',
      'Genetics and Heredity',
      'Variation and Evolution',
      'Ecology and Ecosystem',
      'Pollution and Conservation',
      'Classification of Living Things',
      'Kingdom Monera and Protista',
      'Kingdom Fungi and Plantae',
      'Kingdom Animalia',
    ],
  },
  {
    id: 'economics',
    name: 'Economics',
    emoji: '💰',
    color: '#2e4a7a',
    topics: [
      'Basic Concepts of Economics',
      'Demand and Supply',
      'Elasticity of Demand and Supply',
      'Market Structures',
      'Theory of Consumer Behaviour',
      'Theory of Production',
      'Theory of Costs',
      'National Income',
      'Money and Banking',
      'Inflation and Deflation',
      'Fiscal Policy and Government Budget',
      'Balance of Payments',
      'International Trade',
      'Economic Development and Growth',
      'Agriculture in Nigeria',
      'Industry and Industrialisation',
      'Population and Labour',
      'Public Finance',
      'Poverty and Unemployment',
    ],
  },
  {
    id: 'government',
    name: 'Government',
    emoji: '🏛️',
    color: '#1b2a4a',
    topics: [
      'Meaning and Scope of Government',
      'Democracy and Its Types',
      'Federalism',
      'Constitution and Constitutionalism',
      'Separation of Powers',
      'Legislature — Functions and Types',
      'Executive — Functions and Types',
      'Judiciary — Functions and Independence',
      'Electoral Systems',
      'Political Parties and Party Systems',
      'Public Administration',
      'Local Government',
      'Citizenship and Civic Rights',
      'Human Rights',
      'Pressure Groups and Interest Groups',
      'Colonial Rule in Nigeria',
      'Nigerian Independence and Republic',
      'Military Rule in Nigeria',
      'ECOWAS and African Union',
      'United Nations and International Bodies',
    ],
  },
  {
    id: 'literature',
    name: 'Literature in English',
    emoji: '📚',
    color: '#2e4a7a',
    topics: [
      'Introduction to Literature',
      'Poetry — Features and Analysis',
      'Drama — Structure and Types',
      'Prose — Types and Elements',
      'Figures of Speech',
      'Literary Devices',
      'African Literature',
      'Nigerian Literature',
      'Oral Literature and Folklore',
      'Themes in Literature',
      'Character and Characterisation',
      'Setting and Atmosphere',
      'Plot and Conflict',
      'Point of View and Narrator',
      'Prescribed Texts — Poetry',
      'Prescribed Texts — Drama',
      'Prescribed Texts — Prose',
    ],
  },
  {
    id: 'geography',
    name: 'Geography',
    emoji: '🌍',
    color: '#1b4a2e',
    topics: [
      'Maps and Map Reading',
      'Latitude and Longitude',
      'Rocks and Rock Cycle',
      'Weathering and Erosion',
      'Rivers and River Landforms',
      'Coastal Landforms',
      'Atmosphere and Weather',
      'Climate Types',
      'Soils and Vegetation',
      'Population Geography',
      'Settlement — Rural and Urban',
      'Agriculture — Types and Systems',
      'Mining and Mineral Resources',
      'Industry and Manufacturing',
      'Transport and Communication',
      'Trade and Commerce',
      'Environmental Hazards',
      'West African Geography',
      'Nigerian Geography',
      'World Geography',
    ],
  },
  {
    id: 'agriculture',
    name: 'Agricultural Science',
    emoji: '🌾',
    color: '#2e4a1b',
    topics: [
      'Meaning and Importance of Agriculture',
      'Branches of Agriculture',
      'Land and Soil',
      'Soil Fertility and Management',
      'Irrigation and Drainage',
      'Crop Production — Cereals',
      'Crop Production — Legumes',
      'Crop Production — Root Crops',
      'Crop Production — Vegetables and Fruits',
      'Plant Diseases and Pests',
      'Weed Control',
      'Animal Production — Poultry',
      'Animal Production — Ruminants',
      'Animal Production — Fish Farming',
      'Animal Health and Diseases',
      'Agricultural Tools and Machinery',
      'Farm Management and Records',
      'Agricultural Finance and Credit',
      'Food Storage and Processing',
      'Agricultural Extension',
    ],
  },
  {
    id: 'commerce',
    name: 'Commerce',
    emoji: '🏪',
    color: '#4a2e1b',
    topics: [
      'Introduction to Commerce',
      'Trade — Home and Foreign',
      'Retail Trade',
      'Wholesale Trade',
      'Transport and Communication',
      'Warehousing and Storage',
      'Insurance',
      'Banking — Commercial Banks',
      'Banking — Central Bank',
      'Money and Capital Market',
      'Advertising and Sales Promotion',
      'Consumer Protection',
      'Business Documents',
      'Import and Export Procedures',
      'Entrepreneurship',
      'Co-operative Societies',
      'Public Enterprises',
      'Tourism',
    ],
  },
  {
    id: 'accounting',
    name: 'Financial Accounting',
    emoji: '🧾',
    color: '#1b3a4a',
    topics: [
      'Introduction to Accounting',
      'Double Entry Bookkeeping',
      'Books of Original Entry',
      'Ledger Accounts',
      'Trial Balance',
      'Trading and Profit & Loss Account',
      'Balance Sheet',
      'Bank Reconciliation Statement',
      'Errors and Their Correction',
      'Depreciation',
      'Partnership Accounts',
      'Company Accounts',
      'Non-Profit Organisation Accounts',
      'Accounting Ratios',
      'Cash Flow Statement',
      'Government Accounting',
    ],
  },
  {
    id: 'civic',
    name: 'Civic Education',
    emoji: '🗳️',
    color: '#3a1b4a',
    topics: [
      'Citizenship',
      'Democracy and Good Governance',
      'Rule of Law',
      'Human Rights and Responsibilities',
      'National Values',
      'Corruption and Anti-Corruption',
      'Drug Abuse and Trafficking',
      'HIV/AIDS Awareness',
      'Traffic Laws and Road Safety',
      'Constitution of Nigeria',
      'INEC and Elections',
      'National Symbols',
      'Inter-ethnic Relations',
      'Gender Equality',
      'Community Development',
    ],
  },
  {
    id: 'crk',
    name: 'Christian Religious Studies',
    emoji: '✝️',
    color: '#4a1b1b',
    topics: [
      'Creation and the Fall of Man',
      'Noah and the Flood',
      'Abraham and the Covenant',
      'Moses and the Law',
      'The Judges of Israel',
      'The Monarchy — Saul, David, Solomon',
      'The Prophets — Isaiah, Jeremiah, Amos',
      'The Birth and Early Life of Jesus',
      'The Ministry of Jesus',
      'Miracles of Jesus',
      'Parables of Jesus',
      'The Sermon on the Mount',
      'Death and Resurrection of Jesus',
      'The Holy Spirit and Pentecost',
      'Paul\'s Missionary Journeys',
      'The Early Church',
      'Christian Ethics and Values',
    ],
  },
  {
    id: 'irk',
    name: 'Islamic Studies',
    emoji: '☪️',
    color: '#1b4a3a',
    topics: [
      'Tawheed — Oneness of Allah',
      'The Pillars of Islam',
      'The Pillars of Iman',
      'The Quran — Revelation and Compilation',
      'Sunnah and Hadith',
      'Seerah — Life of the Prophet',
      'The Rightly Guided Caliphs',
      'Islamic Jurisprudence (Fiqh)',
      'Prayer — Salat',
      'Fasting — Sawm',
      'Zakat and Charity',
      'Hajj and Umrah',
      'Islamic Ethics and Morality',
      'Family Law in Islam',
      'Islam in Nigeria',
      'Islamic Scholars of West Africa',
    ],
  },
  {
    id: 'further_maths',
    name: 'Further Mathematics',
    emoji: '∑',
    color: '#2e1b4a',
    topics: [
      'Sets and Logic',
      'Surds and Indices',
      'Polynomials',
      'Rational Functions',
      'Matrices and Transformations',
      'Vectors in 2D and 3D',
      'Complex Numbers',
      'Sequences and Series',
      'Binomial Theorem',
      'Limits and Continuity',
      'Differentiation — Rules and Applications',
      'Integration — Definite and Indefinite',
      'Differential Equations',
      'Permutation, Combination and Probability',
      'Statistics — Distributions',
      'Mechanics — Statics and Dynamics',
    ],
  },
  {
    id: 'technical_drawing',
    name: 'Technical Drawing',
    emoji: '📏',
    color: '#1b2a3a',
    topics: [
      'Drawing Instruments and their Uses',
      'Lines and Lettering',
      'Geometric Constructions',
      'Plane Figures',
      'Orthographic Projection',
      'Isometric Drawing',
      'Oblique Drawing',
      'Sections and Sectional Views',
      'Dimensioning',
      'Building Drawing',
      'Electrical and Electronic Drawing',
      'CAD Introduction',
    ],
  },
];

export default SUBJECTS;
